spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
  data:
    mongodb:
      uri: localhost:27017/tradestore
      database: tradestore
kafka:
  bootstrap-servers: localhost:9092
  topic: trades.incoming

tradestore:
  timezone: Asia/Kolkata
